### ISSUE TITLE
Decrease time to wait for network interface

### ISSUE THREAD

**Issue by vollstock** [Tooloop/Tooloop-OS#23]
If there is no network connection, Ubuntu seems to wait for 5 minutes.
This is of course a looooong time if we deploy an offline unit. ;-)

[Here is a suggested solution](https://ubuntuforums.org/showthread.php?t=2323253&p=13484073#post13484073) to simply decrease that.

What is the lowest reasonable number here?

**Comment by DigitalFlodur** [comment]
30 seconds?

**Comment by vollstock** [comment]
Seems reasonable and it’s also the time, someone suggested in the linked Ubuntu forum. 

I still want to invest into this a little more.
When is Ubuntu waiting? 
If a cable is plugged in but no connection can be established? 
If no cable is connected at all?
In the first case a longer period seems more appropriate then in the latter.

**Comment by vollstock** [comment]
this is fixed in the 22.04 branch
