### ISSUE TITLE
Trouble setting locale

### ISSUE THREAD

**Issue by oleprinds** [Tooloop/Tooloop-OS#30]
When running the install script, I get perl warnings and an error installing the settings server dependencies.

The perl warnings look like this and appear while installing git, during the upgrade, and while installing base packages..

```
perl: warning: Setting locale failed.

perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

locales is also getting upgraded:
```
Setting up locales (2.23-0ubuntu11.2) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Generating locales (this might take a while)...
  en_AG.UTF-8... done
  en_AU.UTF-8... done
  en_BW.UTF-8... done
  en_CA.UTF-8... done
  en_DK.UTF-8... done
  en_GB.UTF-8... done
  en_HK.UTF-8... done
  en_IE.UTF-8... done
  en_IN.UTF-8... done
  en_NG.UTF-8... done
  en_NZ.UTF-8... done
  en_PH.UTF-8... done
  en_SG.UTF-8... done
  en_US.UTF-8... done
  en_ZA.UTF-8... done
  en_ZM.UTF-8... done
  en_ZW.UTF-8... done
Generation complete.
```

But the real problem is that the settings server fails to install, due to pip not being able to install flask
```
Setting up python-wheel (0.29.0-1) ...
Processing triggers for libc-bin (2.23-0ubuntu11.2) ...
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

To fix this I had to set LC_ALL and LC_CTYPE manually
```
~$ export LC_CTYPE="en_US.utf8"
~$ export LC_ALL="en_US.utf8"
```

I used lower case utf8, because thats how locale -a returns them:
```
~$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```

After that I ran the install-dependencies.sh from the settings server again, and it now works, but is there some way to make the locale settings work, that could be included in the install script?

I tried the same on multiple computers now.. This time i chose en_US.utf8 while installing ubuntu server 16.04, but have also tried installing ubuntu with other locales, with no luck..

Full output is here [tooloop_install_output.txt](https://github.com/vollstock/Tooloop-OS/files/5094964/tooloop_install_output.txt)

**Comment by vollstock** [comment]
Does this still happen? I noticed, that you are running a fork and have a branch for Ubuntu 20.04.
I am actively working on a 22.04 version in a branch here.

Maybe we can close this as I have never seen this error and can’t reproduce it.

**Comment by oleprinds** [comment]
Yes, we can close this now. I think the error appeared when installing tooloop on ubuntu 16.04.. I haven't seen it on 18.04 or 20.04. Sounds good with the 22 branch.
